### ISSUE TITLE
Can you add/open the method to return dictionary of properties?

### ISSUE THREAD

**Issue by Vyeche** [jchristian/yahoo_stock_quotes#2]
Hi,

I'm trying to access the properties without the "\"Google Inc.\"" characters. I noticed that the IEnumerable returns a hidden dictionary. Is it possible that those can be cleaned?

Will it be possible to just ask for one quote and get its properties, instead of asking for multiple?

**Comment by jchristian** [comment]
The quotes should be removed now.
