### ISSUE TITLE
Fields with comma character break CSV parsing

### ISSUE THREAD

**Issue by t3rse** [jchristian/yahoo_stock_quotes#4]
var quotes = quote_service.Quote("DHI").Return(QuoteReturnParameter.Symbol,
                                                                    QuoteReturnParameter.Name,
                                                                    QuoteReturnParameter.LatestTradePrice,
                                                                    QuoteReturnParameter.LatestTradeTime);

DHI comapany name includes comma: D.R. Horton, Inc.

**Comment by jchristian** [comment]
Sorry this is a couple months late.  This should be fixed now.  I introduced an actual csv parsing library to handle the file parsing.

**Comment by t3rse** [comment]
Awesome, thanks.
